Encuestas/Models/PerfilesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Encuestas.Models
{
    public class PerfilesViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Este campo es requerido")]
        [MinLength(2, ErrorMessage = "El dato no es un nombre")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Solo son aceptadas letras")]
        public String Nombre { get; set; }
        [Required(ErrorMessage = "Este campo es requerido")]
        [MinLength(4, ErrorMessage = "El dato no es un apellido")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Solo son aceptadas letras")]
        public String ApellidoPaterno { get; set; }
        [Required(ErrorMessage = "Este campo es requerido")]
        [MinLength(4, ErrorMessage = "El dato no es un apellido")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Solo son aceptadas letras")]
        public String ApellidoMaterno { get; set; }
        [Required(ErrorMessage = "Este campo es requerido")]
        [Range(14, 150, ErrorMessage = "Tienes que tener una edad aceptada")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Solo se aceptan números")]
        public int Edad { get; set; }
        [Required(ErrorMessage = "Este campo es requerido")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode =true, DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime FechaNacimiento { get; set; }
        //[Required(ErrorMessage = "Se necesita de una fotografía")]
        public byte[] Foto { get; set; }
        public int IdUser { get; set; }
    }
}

Encuestas/Controllers/PerfilesController.cs
using Encuestas.Models;
using Estadisticas.Modelo;
using Estadisticas.Negocios;
using Estadisticas.Negocios.Contrato;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Encuestas.Controllers
{
    public class PerfilesController : Controller
    {
        private readonly IPerfilesNegocio db = new PerfilesNegocio();
        private readonly IUsuarioNegocio udb = new UsuariosNegocio();
        // GET: Perfiles
        [HttpGet]
        public ActionResult Registrar()
        {
            ViewBag.IdUser = new SelectList(udb.GetUsuarios(), "Id", "email");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar([Bind(Include = "nombre, apellidoPaterno, apellidoMaterno, edad, fechaNacimiento", Exclude ="Foto")] PerfilesViewModel per, int IdUser)
        {
            if (ModelState.IsValid)
            {
                byte[] imageData = null;
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase poImgFile = Request.Files["Foto"];

                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        imageData = binary.ReadBytes(poImgFile.ContentLength);
                    }
                }

                Perfiles perfil = new Perfiles { Nombre = per.Nombre, ApellidoPaterno = per.ApellidoPaterno, ApellidoMaterno = per.ApellidoMaterno, Edad = per.Edad, FechaNacimiento = per.FechaNacimiento }; 
                List<Usuarios> usuarios = new List<Usuarios>();
                Usuarios usuario = new Usuarios { Id = IdUser };
                perfil.IdUser = IdUser;
                perfil.Foto = imageData;
                if (db.Insert(perfil))
                {
                    return RedirectToAction("SigIn", "Seguridad");
                }
                else
                {
                    ModelState.AddModelError("error_registro", "El perfil no se registro correctamente");
                    return View();
                }
            }
            ViewBag.IdUser = new SelectList(udb.GetUsuarios(), "Id", "email");
            return View();
        }
    }
}

Encuestas/Views/Perfiles/Registrar.cshtml
@model Encuestas.Models.PerfilesViewModel
@{
    ViewBag.Title = "Registrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <title>Registro de Usuarios</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <br />
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            Registro del perfil
                        </div>
                    </div>
                    <div class="card-body">
                        @using (@Html.BeginForm("Registrar", "Perfiles", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control input-group-sm", placeholder = "Ingresa tu Nombre", id = "Nombre", required = "required" })
                                @Html.ValidationMessageFor(model => model.Nombre, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control input-group-sm", placeholder = "Ingresa tu apellido paterno", id = "ApellidoPaterno", required = "required" })
                                @Html.ValidationMessageFor(model => model.ApellidoPaterno, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control input-group-sm", placeholder = "Ingresa tu apellido materno", id = "ApellidoMaterno", required = "required" })
                                @Html.ValidationMessageFor(model => model.ApellidoMaterno, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.TextBoxFor(model => model.Edad, new { @class = "form-control input-group-sm", placeholder = "Ingresa tu edad", id = "Edad", required = "required" })
                                @Html.ValidationMessageFor(model => model.Edad, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.TextBoxFor(model => model.FechaNacimiento, "{0:dd/MM/yyyy}", new { @class = "form-control input-group-sm", placeholder = "Fecha de nacimiento día-mes-año", id = "FechaNacimiento", required = "required" })
                                @Html.ValidationMessageFor(model => model.FechaNacimiento, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Foto, new { @class = "col-md-2 control-label", required = "required" })
                                <div class="col-md-10">
                                    <input type="file" name="Foto" id="File" accept=".png,.jpg,.jpeg" />
                                </div>
                                @Html.ValidationMessageFor(model => model.Foto, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.DropDownList("IdUser", null, new { @class = "dorm-control input-sm" })
                            </div>
                            <div class="form-group">
                                @Html.ValidationMessage("error_registro", new { @class = "text-danger" })
                                <input type="submit" class="btn btn-sm btn-success float-right" value="Register" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>